#!/bin/bash

# Run this from the artresources folder to create tx files from png texture files.

eval $( find artresources/textures | grep png$ | sed \
    's|\(.*/\)\(.*\)png|$SHARKENGINE_HOME/tools/png2tx \1\2png assets/textures/\2tx;|' );
