#!/bin/bash

function error {
  echo "Error. Usage:"
  echo "    set_apple_proj [ios | osx] [generic | editable]"
  exit
}

if [ ! "$1" = "ios" ] && [ ! "$1" = "osx" ]; then
  error
fi

if [ "$2" = "generic" ]; then
  sed -i '' -e "s/$(echo $SHARKENGINE_HOME | sed -e 's/[\/&]/\\&/g')/___SHARKENGINE_HOME___/g" \
      -e "s/$(echo $SHARKSOUND_HOME | sed -e 's/[\/&]/\\&/g')/___SHARKSOUND_HOME___/g" \
      $SHARKENGINE_HOME/platforms/apple/build/$1/Sharkengine_$1.xcodeproj/project.pbxproj
elif [ "$2" = "editable" ]; then
  sed -i '' -e "s/___SHARKENGINE_HOME___/$(echo $SHARKENGINE_HOME | sed -e 's/[\/&]/\\&/g')/g" \
      -e "s/___SHARKSOUND_HOME___/$(echo $SHARKSOUND_HOME | sed -e 's/[\/&]/\\&/g')/g" \
      $SHARKENGINE_HOME/platforms/apple/build/$1/Sharkengine_$1.xcodeproj/project.pbxproj
else
  error
fi
